### ISSUE TITLE
BE01: Validate File Format 

### ISSUE THREAD

**Issue by nnh53** [PiedTeam/DreameCloneTraining-BE-Project#2]
(US-01)
- Description:
    - Implement validation checks to ensure imported FILE meets the required format.
    - Handling the file name ( name file +.en/.vi) and format with an extension ( xlsx/ xls/ csv)
       + Example:  Products Dreame.vi.xlsx, Products Dreame.en.csv
    - Ensure the file size must smaller or equal than 10mb
    - If the file is corrupted (cannot open, cannot read) response the error

- Reason for the estimated point:
    - Never done it and have 3 goal know but khow how to handle it 
- Solution:
  - name: splice name file check extension file and define language 
  - size file: use formidable to check size file

- Approval Standards:
    - Receive file from postman
    - Return the corresponding error message 
    - That file can be open and read (change PNG to .xlsx)

**Comment by lcaohoanq** [comment]
@nnh53 
- File phải mở được
- Tên file không được chứa kí tự đặc biệt
- Ngôn ngữ phải được hỗ trợ (vi, en)
- Phần extension của file phải đúng chuẩn (xls, xls, csv)

**Comment by nnh53** [comment]
@lcaohoanq nếu mà file PNG đổi thành .xlsx thì phải báo đc lỗi "Không phải file excel"

**Comment by nnh53** [comment]
@lcaohoanq please change status of this issue and remove the commit 3663e02 doc: update doc. just bring the image and report to me at this issue

**Comment by lcaohoanq** [comment]
@nnh53 
This feature is only import 1 file or multiple file, the logic now is handle 1 file only

**Comment by nnh53** [comment]
That is correct, we only allow 1 file at a time, contact @hoangday185

**Comment by lcaohoanq** [comment]
@nnh53 
I have a problem, there is my route for handling the file
![image](https://github.com/PiedTeam/DreameCloneTraining-BE-Project/assets/136492579/7ed15fa1-b1eb-4e6a-87fa-dc557f318e97)
I'm using `mutler` for responsibility the upload file... come to validate logic, as default it will upload the file into folder /module/upload whenever the file is valid or not
- My first solution is change the order of parameter like: 
```js 
fileRouter.post('/upload', fileValidator, upload, upload.single('myFile')) 
```
- But it's not work as expected, the upload need to come first for take the file data, so that the other validate like middleware, controller start to work
- My second solution is modifier logic inside middleware, for accept write file or not after validation
![image](https://github.com/PiedTeam/DreameCloneTraining-BE-Project/assets/136492579/06f60322-e990-4f69-b97d-90e864d9163f)
- The idea is using the buffer instead
![image](https://github.com/PiedTeam/DreameCloneTraining-BE-Project/assets/136492579/b564f968-dfc9-425c-a1bd-3ea08b49b392)
- The valiate will work well but meet the last one, `does file can be opened`, it failed because the key `buffer` is not in `FileType` 
- ![image](https://github.com/PiedTeam/DreameCloneTraining-BE-Project/assets/136492579/5bb44cc9-88fe-4cc6-b7bc-001d5c598d4b)
![image](https://github.com/PiedTeam/DreameCloneTraining-BE-Project/assets/136492579/c0a766d8-39d0-4318-88fb-b42e23ca76b6)
- This is a file create with buffer structure, there cause the conflict with `FileType at file.schema.ts`
![image](https://github.com/PiedTeam/DreameCloneTraining-BE-Project/assets/136492579/b507faa6-8628-4f60-a804-f8134ae7437f)

Is there any solution, thanks

**Comment by nnh53** [comment]
- Move to sprint 3

**Comment by nnh53** [comment]
- Not handle upload corrupted file after upload to the server
- From 3 point to 2.5 point

**Comment by lcaohoanq** [comment]
> * Move to sprint 3

Okay
